Lock version of k8s python module to 17.17.0
Later versions introduce changes in module behavior and cause problems with
NHD:

AttributeError: module 'kubernetes.client' has no attribute 'V1Event'